// Authoritative geo seed.
//
// Province → district → tehsil data lives in `pakistan-geo.json`, generated
// from `apps/api/data/pakistan-tehsils.csv` (mirror of the canonical
// "Pakistan structure" Google Sheet). To refresh, replace the CSV and
// re-run `npx tsx scripts/build-pakistan-geo.ts`.
//
// Police-station data is kept inline below.

import pakistanGeoJson from './pakistan-geo.json';

type RawGeo = Record<string, Record<string, string[]>>;
const PAKISTAN_GEO_RAW = pakistanGeoJson as RawGeo;

export const RAW_POLICE_STATIONS_BY_PROVINCE = {
  Punjab: {
    Attock: [
      'ANF',
      'Anti Corruption',
      'Attock Khurd',
      'Basal',
      'Bathar',
      'City Attock',
      'City Hassan Abdal',
      'Fateh Jang',
      'Hazro',
      'Injra',
      'Jand',
      'New Air port',
      'Pindigheb',
      'Railway',
      'Rangoo',
      'Saddar Attock',
      'Saddar Hassan Abdal',
    ],
    Bahawalpur: [
      'Abbas Nagar',
      'Anit Corruption',
      'Baghdad-ul-Jadeed',
      'Cantt.',
      'Chani Goth',
      'Chowki Railway Ahmadpur East',
      'City Ahmadpur East',
      'City Hasilpur',
      'City Yazman',
      'Civil Lines',
      'Dera Nawab Sahib',
      'Derawar',
      'Dhoor Kot',
      'FIA',
      'Head Rajkan',
      'Inayati',
      'Khairpur Tamewali',
      'Kotwali',
      'Musafir Khana',
      'Nowshehra Jadid',
      'Qaimpur',
      'Railway Bahawalpur',
      'Railway Khanpur',
      'Railway Samma Satta',
      'Saddar Ahmadpur East',
      'Saddar Bahawalpur',
      'Saddar Hasilpur',
      'Saddar Yazman',
      'Samma Sattta',
      'Uch Sharif',
    ],
    Bhakkar: [
      'Anti Corruption Bhakkar',
      'Behal Bhakkar',
      'Chandni Chowk',
      'City Bhakkar',
      'City Darya Khan',
      'Dullewala',
      'Haidarabad',
      'Jandanwala',
      'Kalur Kot',
      'Mankaira',
      'Railway Bhakkar',
      'Saddar Bhakkar',
      'Saddar Darya Khan',
      'Sara-e-Mohajar',
    ],
    Bhawalnagar: [
      'Anti Corruption',
      'Bakhshan Khan',
      'CIA',
      'City A/Division Bahawalnagar',
      'City A/Division Chishtian',
      'City B/Division Bahawalnagar',
      'City B/Division Chishtian',
      'City Haroonabad',
      'Dahranwala',
      'Dunga Bunga',
      'Faqirwali',
      'Fortabbas',
      'Ghumand Pur',
      'Khichiwala',
      'Maclod Gunj',
      'Madrassa',
      'Mandi Sadiq Gunj',
      'Maroot',
      'Minchinabad',
      'Railway',
      'Saddar Bahawalnagar',
      'Saddar Chishtian',
      'Saddar Haroonabad',
      'Shaher Fareed',
      'Takht Mahal',
    ],
    Chakwal: [
      'Choa Saidan Shah',
      'City Chakwal',
      'City Talagang',
      'Dhudial',
      'Duhman',
      'Kallar Kahar',
      'Lawa',
      'Neela',
      'Saddar Chakwal',
      'Saddar Talagang',
      'Tamman',
    ],
    Chiniot: [
      'Bhowana',
      'Chenab Nagar',
      'City',
      'City Chiniot',
      'Kanidwal',
      'Kot Wasawa',
      'Lalian',
      'Langrana',
      'Muhammad Wala',
      'Railway Police Post',
      'Rajoya',
      'Saddar  Chiniot',
    ],
    'Dera Ghazi Khan': [
      'Anti-Corruption',
      'B-Division',
      'BMP Post D.G.Khan',
      'BMP Post Taunsa Sharif',
      'Choti',
      'City',
      'City, Taunsa Sharif',
      'Civil Line',
      'Darhama',
      'Darkhast Jamal Khan',
      'FIA',
      'Gaddai',
      'Jhoke Utra',
      'Kala',
      'Kot Chutta',
      'Kot Mubarak',
      'Railway',
      'Raitra',
      'Saddar',
      'Saddar, Taunsa Sharif',
      'Sakhi Sarwar',
      'Shah Saddar Din',
      'Vehova',
    ],
    Faisalabad: [
      'ANF',
      'Anti-Corruption',
      'ATA',
      'Bahlak',
      'Balochni',
      'Batala Colony',
      'Buchiana',
      'Chak Jhumra',
      'Civil Lines',
      'D-Type Colony',
      'Dijkot',
      'F.I.A.',
      'Factory Area',
      'FEDMC',
      'G. M. Abad',
      'Garh',
      'Gulberg',
      'Jaranwala City',
      'Jaranwala Sadar',
      'Jhang Bazar',
      'Khurrianwala',
      'Kotwali',
      'Kurr',
      'Lundianwala',
      'Madina Town',
      'Mamukanjan',
      'Mansoor Abad',
      'Millat Town',
      'Muridwala',
      'Nishat Abad',
      'Peoples Colony',
      'Rail Bazar',
      'Railway',
      'Railway Jaranwala',
      'Raza Abad',
      'Rodala Road',
      'Roshanwala',
      'Sadar',
      'Sahianwala',
      'Samanabad',
      'Samundri City',
      'Samundri Sadar',
      'Sandal Bar',
      'Sargodha Road',
      'Satiana',
      'Tandlianwala City',
      'Tandlianwala Sadar',
      'Tarkhani',
      'Thikriwala',
      'Women',
    ],
    Gujranwala: [
      'Ahmad Nagar',
      'Ali Pur',
      'Anti Corruption',
      'Aroop',
      'Baghbanpura',
      'Cantt',
      'CIA',
      'City Kamoke',
      'City Wazirabad',
      'Civil Line',
      'CTD',
      'Dhullay',
      'Eminabad',
      'Ferozewala',
      'FIA',
      'Garjakh',
      'Ghakhar Mandi',
      'Jinnah Road',
      'Khiali',
      'Kot Ladha',
      'Kotwali',
      'Ladhewala Waraich',
      'Model Town',
      'Noushera Virkan',
      'Peoples Colony',
      'Police Line Gujranwala',
      'Qilla Dedar Singh',
      'Railway',
      'Sabzi Mandi',
      'Sadar Gujranwala',
      'Sadar Kamoke',
      'Sadar Wazirabad',
      'Satellite Town',
      'Sohdra',
      'Tatlay Aali',
      'Wahndo',
    ],
    Gujrat: [
      'A/Division',
      'Anti Corruption',
      'B/Division',
      'Bolani',
      'City Jalalpur Jattan',
      'City Lalamusa',
      'City Sarai Alamgir',
      'Civil Line',
      'Daulat Nagar',
      'Dinga',
      'FIA',
      'Guliana',
      'Industrial Estate Phase 2',
      'Kakrali',
      'Karianwala',
      'Kharian Cantt.',
      'Kunjah',
      'Larry Adda',
      'Mangowal',
      'Railway',
      'Rehmania',
      'Sadar Gujrat',
      'Sadar Jalapur Jattan',
      'Sadar Kharian',
      'Sadar Lalamusa',
      'Sadar Sarai Alamgir',
      'Shaheen Chowk',
      'Tanda',
    ],
    Hafizabad: [
      'CITY HAFIZABAD',
      'CITY PINDI BHATTIAN',
      'JALAL PUR BHATTIAN',
      'KALEKE MANDI',
      'KASESAY',
      'KASOKE',
      'SADAR HAFIZABAD',
      'SADAR PINDI BHATTIAN',
      'SUKHEKE MANDI',
      'VENEKE TARAR',
    ],
    Jhang: [
      '18-Hazari',
      'Ahmad Pur Sial',
      'City Jhang',
      'City Shorkot',
      'Garh Maharaja',
      'Kot Shakir',
      'Kotwali',
      'Massan',
      'Mochiwala',
      'Qadir Pur',
      'Railway',
      'Sadar Jhang',
      'Satellite Town',
      'Shorkot Cannt.',
      'Waryam',
    ],
    Jhelum: [
      'ANF Dina',
      'Chotala',
      'City',
      'Civil Lines',
      'Dina',
      'Domeli',
      'Jalalpur Sharif',
      'Kala Gujran',
      'Lilla',
      'Mangla Cantt',
      'Pind Dadan Khan',
      'Railway',
      'Saddar',
      'Sohawa',
    ],
    Kasur: [
      'A Division',
      'Allahabad',
      'Anti Corruption',
      'B Division',
      'Changa Manga',
      'City Chunian',
      'City Pattoki',
      'City Phool Nagar',
      'Ganda Singh Wala',
      'Kanganpur',
      'Khudian',
      'Kot Radha Kishan',
      'Mandi Usman Wala',
      'Mustafabad',
      'Railway Kasur',
      'Raja Jang',
      'Sadar Chunian',
      'Sadar Kasur',
      'Sadar Pattoki',
      'Sadar Phool Nagar',
      'Sarai Mughal',
      'Theh Sheikhum',
    ],
    Khanewal: [
      'Abdul Hakeem',
      'Adda Baara Meel',
      'Chab kallan',
      'City Jehanian',
      'City Kabirwala',
      'City Khanewal',
      'City Mianchannu',
      'Hawaili koranga',
      'Kacha Kho',
      'Kohna',
      'Makhdoom Pur',
      'Nawan Shehar',
      'Railway Kabirwala',
      'Railway Khanewal',
      'Railway Mianchannu',
      'Saddar Kabirwala',
      'Saddar Khanewal',
      'Saddar Mianchannu',
      'Sirae Saddhu',
      'Thatha Sadiq Abad',
      'Tulamba',
    ],
    Khushab: [
      'City Jauharabad',
      'Jaura Kalan',
      'Katha Saghral',
      'Khushab',
      'Mitha Tiwana',
      'Naushera',
      'Noorpur Thal',
      'Quaidabad',
      'Saddar Jauharabad',
    ],
    Lahore: [
      'Akbri Gate',
      'Anti Corruption',
      'Anti Narcotics Force',
      'Badami Bagh',
      'Baghbanpura',
      'Barki',
      'Batapur',
      'Bhatti Gate',
      'Chung',
      'CIA',
      'Civil Line',
      'Custom House Cell',
      'Data Darbar',
      'Defence A',
      'Defence B',
      'Defence C',
      'Factory Area',
      'Faisal Town',
      'FIA',
      'Garden Town',
      'Garhi Shahu',
      'Gawal Mandi',
      'Ghalib Market',
      'Ghazia Abad',
      'Green Town',
      'Gujjar Pura',
      'Gulberg',
      'Gulshan Iqbal',
      'Gulshan Ravi',
      'Hair',
      'Hanjarwal',
      'Harbanspura',
      'Hydyara',
      'Ichhra',
      'Iqbal Town',
      'Islam Pura',
      'Johar Town',
      'Kahna',
      'Kot Lakhpat',
      'Lady Race Course',
      'Larry Adda',
      'Liaqat Abad',
      'Lohari Gate',
      'Lower Mall',
      'Lyttan Road',
      'Manawan',
      'Manga Mandi',
      'Masti Gate',
      'Millat Park',
      'Misri Shah',
      'Mochi Gate',
      'Model Town',
      'Mozang',
      'Mughalpura',
      'Muslim Town',
      'Mustafa Abad',
      'Mustafa Town',
      'Naseer Abad',
      'Nawab Town',
      'Nawan Kot',
      'New Anarkali',
      'Nishter Colony',
      'North Cantt.',
      'Noulakha',
      'Old Anarkali',
      'Qilla Gujjar Singh',
      'Quaid e Azam Industrial Area',
      'Race Course',
      'Railway Lahore',
      'Railway Mughalpura',
      'Railway Raiwind',
      'Raiwind',
      'Rang Mahal',
      'Ravi Road',
      'Sabzazar',
      'Samanabad',
      'Sanda',
      'Sarwar Road',
      'Sattokatla',
      'Shad Bagh',
      'Shadman',
      'Shafique Abad',
      'Shahdara',
      'Shahdara Town',
      'Shalimar',
      'Shera Kot',
      'South Cantt.',
      'Sundar',
      'Tibi City',
      'Town Ship',
      'Wahdat Colony',
      'Yakki Gate',
    ],
    Layyah: [
      'Anti Corruption',
      'Choubara',
      'Chowk Azam',
      'City Layyah',
      'Fateh Pur',
      'FIA',
      'Karor',
      'Kot Sultan',
      'Peer Jaggi',
      'Railway',
      'Saddar Layyah',
    ],
    Lodhran: [
      'City Dunya Pur',
      'City Kehror Pacca',
      'City Lodhran',
      'Dhanote',
      'Galley Wal',
      'Jalla Arain',
      'Qureshi Wala',
      'Railway',
      'Saddar Dunya Pur',
      'Saddar Kehror Pacca',
      'Saddar Lodhran',
    ],
    'Mandi Bahauddin': [
      'Bhagat',
      'City M.B.Din',
      'Civil Line',
      'Gojra',
      'Kuthiala Sheikhan',
      'Malakwal',
      'Miana Gondal',
      'Pahrianwali',
      'Phalia',
      'Qadirabad',
      'Railway',
      'Sadar M.B.Din',
    ],
    Mianwali: [
      'ANF',
      'Anti Corruption',
      'Bhangi Khel',
      'Chakrala',
      'Chapri',
      'Chidru',
      'City',
      'Daud Khel',
      'Easa Khel',
      'Harnoli',
      'Kala Bagh',
      'Kamar Mushani',
      'Kundian',
      'Makrwal',
      'Mochh',
      'Musa Khel',
      'Pai Khel',
      'Phir Pehai',
      'Piplan',
      'Railway',
      'Sadar',
      'Wan Bachran',
    ],
    Multan: [
      'Alpha',
      'ANF',
      'Anti-Corruption',
      'Bahauddin Zakriya',
      'Basti Malook',
      'Bohar Gate',
      'Budhla Sant',
      'Cantt Multan',
      'Chehliyak',
      'City Jalalpur Pirwala',
      'City Shujabad',
      'Custom',
      'Dehli Gate',
      'Dolat Gate',
      'FIA',
      'Gulgasht',
      'Haram Gate',
      'Jaleelabad',
      'Kup',
      'Lohari Gate',
      'Makhdoom Rasheed',
      'Mumtazabad',
      'Muzafarabad',
      'New Multan',
      'Old Kotwali',
      'Pak Gate',
      'Qadir Pur Ran',
      'Qutab Pur',
      'Railway',
      'Rajaram (Shujabad)',
      'Saddar Jalalpur Pirwala',
      'Saddar Multan',
      'Saddar Shujabad',
      'Seetal Marri',
      'Shah Rukne Alam',
      'Shah Shamas',
      'Women Police Center',
    ],
    Muzaffargarh: [
      'Anti Corruption',
      'Bait Mir Hazar',
      'City Ali Pur',
      'City Muzaffargarh',
      'Civil Lines',
      'Daira Din Panah',
      'Jatoi',
      'Khairpur Sadaat',
      'Khangarh',
      'Kot Addu',
      'Kot Addu Saddar',
      'Kundai',
      'Mehmood Kot',
      'Qasba Gujrat',
      'Qureshi',
      'Railway',
      'Rangpur',
      'Rohilanwali',
      'Saddar Alipur',
      'Saddar Muzaffargarh',
      'Sanawan',
      'Sarwar Shaheed',
      'Sarwar Shaheed Saddar',
      'Seetpur',
      'Shah Jamal',
      'Shehr Sultan',
    ],
    'Nankana Sahib': [
      'Barra Ghar',
      'City Nankana Sahib',
      'City Sangla Hill',
      'City Shahkot',
      'Mandi Faiz Abad',
      'Mangtawala',
      'Railway Chuki Sangle Hill',
      'Railway Jaranwala',
      'Saddar Nankana Sahib',
      'Saddar Sangla Hill',
      'Saddar Shahkot',
      'Syed wala',
      'Warbartan',
    ],
    Narowal: [
      'Ahmad Abad',
      'Anti Corruption',
      'Baddo Malhi',
      'Chak Amru',
      'City Narowal',
      'City Shakargarh',
      'Kot Nainan',
      'Lessar Kalan',
      'Niddoke',
      'Noor Kot',
      'Railway Police Post',
      'Rayya Khas',
      'Saddar  Shakargarh',
      'Saddar Narowal',
      'Shah Gharib',
      'Zafarwal',
    ],
    Okara: [
      'A-Division',
      'Anti-corruption',
      'B-Division',
      'Basirpur',
      'Cantt Okara',
      'Chorasta Mian Khan',
      'Chuchak',
      'City Depalpur',
      'City Renala Khurd',
      'Gogera',
      'Haveli Lakha',
      'Hujra Shah Muqeem',
      'Mandi Ahmad Abad',
      'Railway Police Post, Basirpur',
      'Railway Police Post, Okara',
      'Ravi',
      'Sadar Depalpur',
      'Sadar Renala Khurd',
      'Saddar Okara',
      'Satghara',
      'Shahbore',
      'Shergarh',
    ],
    Pakpattan: [
      'Ahmed Yar',
      'Anti-Corruption',
      'Chak Bedi',
      'City Arifwala',
      'City Pakpattan',
      'Dal Waryam',
      'Farid Nagar',
      'Kalyana',
      'Malka Hans',
      'Qabula Sharif',
      'Railway Police Post',
      'Rang Shah',
      'Saddar Arifwala',
      'Saddar Pakpattan',
    ],
    'Rahim Yar Khan': [
      'Aab-e-Hayat',
      'Abadpur',
      'Ahmedpur Lama',
      'Airport',
      'Anti-Corruption',
      'Bhong',
      'Choki Railway RYK',
      'City A Division',
      'City B Division',
      'City C Division',
      'City Khanpur',
      'City Liaqatpur',
      'City Sadiqabad',
      'FIA',
      'Iqbalabad',
      'Islam Garh',
      'Kot Sabzal',
      'Kot Samaba',
      'Machka',
      'Manthar',
      'Pacca Laran',
      'Railway Khanpur',
      'Rukanpur',
      'Sadar Sadiqabad',
      'Saddar Khanpur',
      'Saddar Liaqatpur',
      'Saddar Rahim Yar Khan',
      'Sehja',
      'Shedani',
      'Tabassam Shaheed',
      'Taranda Muhammad Panah',
      'Zahir Peer',
    ],
    Rajanpur: [
      'Bangla Ichaa',
      'BMP Barra',
      'BMP Bhandowala',
      'BMP Chacha',
      'BMP Dilber',
      'BMP Dooli',
      'BMP Harrand',
      'BMP Jhatro',
      'BMP Khaan',
      'BMP Khalchas',
      'BMP Khumbi',
      'BMP Kot Rom',
      'BMP Marri',
      'BMP Mughal',
      'BMP Muranj',
      'BMP Nili Lakri',
      'BMP Sheikhwala',
      'City Fazilpur',
      'City Jampur',
      'City Rajanpur',
      'Goth Mazari',
      'Hajipur',
      'Hanif Ghauri Shaheed Dajal',
      'Harrand',
      'Kot Mithan',
      'Lal Garh',
      'Muhammadpur',
      'Rojhan',
      'Sabzani',
      'Saddar Fazilpur',
      'Saddar Jampur',
      'Saddar Rajanpur',
      'Shahwali',
      'Sonmiani',
      'Umer Kot',
    ],
    Rawalpindi: [
      'ACE',
      'Airport',
      'ANF',
      'Banni',
      'Cantt.',
      'Chakri',
      'Chountra',
      'City Rawalpindi',
      'Civil Line',
      'CTD',
      'Dhamiyal',
      'FIA',
      'Ganjmandi',
      'Gujar Khan',
      'Jatli',
      'Kahuta',
      'Kallar Syedan',
      'Kotli Sattian',
      'Mandra',
      'Morgah',
      'Murree',
      'Naseerabad',
      'New Town',
      'Patriata',
      'Phagwari',
      'Pir Wadhai',
      'RA Bazar',
      'Race Course',
      'Railway',
      'Ratta Amral',
      'Rawat',
      'Saddar Beroni',
      'Saddar Wah Cantt.',
      'Sadiqabad',
      'Taxila',
      'Wah Cantt.',
      'Waris Khan',
      'Westridge',
      'Women',
    ],
    Sahiwal: [
      'Anti Corruption',
      'Bahadar Shah',
      'City Chichawatni',
      'City Sahiwal',
      'Civil Line',
      'Dera Rahim',
      'Fareed Town',
      'Fateh Sher',
      'Ghala Mandi',
      'Ghaziabad',
      'Harappa',
      'Kameer',
      'Kassowal',
      'Noor Shah',
      'Okanwala Bangla',
      'Railway',
      'Saddar Chichawatni',
      'Shah Kot',
      'Yousafwala',
    ],
    Sargodha: [
      'Anti-Corruption',
      'Atta Shaheed',
      'Bhagtanwala',
      'Bhera',
      'Cantt',
      'City Bhalwal',
      'City Sargodha',
      'Factory Area',
      'FIA',
      'Jhal Chakian',
      'Jhawarian',
      'Karana',
      'Kotmomin',
      'Laksian',
      'Mela',
      'Miani',
      'Midh Ranjha',
      'Phullarwan',
      'Railway',
      'S. Town',
      'Saddar Bhalwal',
      'Saddar Sargodha',
      'Sahiwal',
      'Sajid Shaheed',
      'Shahnikdar',
      'Shahpur City',
      'Shahpur Saddar',
      'Sillanwali',
      'Tirkhanwala',
      'Urban Area',
    ],
    Sheikhupura: [
      'A-Division City',
      'Anti Corruption',
      'B-Division City',
      'Bhikhi',
      'CIA',
      'City Farooqabad',
      'City Muridke',
      'Factory Area',
      'Ferozewala',
      'Housing Colony',
      'Khanqah Dogran',
      'Mananwala',
      'Narang Mandi',
      'Railway Police',
      'Sadar Farooqabad',
      'Sadar Muridke',
      'Sadar Sheikhupura',
      'Safdarabad',
      'Sharqpur Sharif',
    ],
    Sialkot: [
      'Airport',
      'ANF',
      'Anti Corruption',
      'Badiana',
      'Bambhanwala',
      'Begowala',
      'Cantt',
      'City Daska',
      'City Pasrur',
      'Civil Line',
      'Haji Pura',
      'Head Marala',
      'Kotli Loharan',
      'Kotli Said Mir',
      'Kotowali',
      'Motra',
      'Murad Pur',
      'Neka Pura',
      'Phaloura',
      'Phukliyan',
      'Qila Kalarwala',
      'Railway Police',
      'Rang Pura',
      'Sabzpir',
      'Sadar Daska',
      'Sadar Pasrur',
      'Sadar Sialkot',
      'Sambrial',
      'Satrah',
      'Ugoki',
    ],
    'Toba Tek Singh': [
      'Aroti',
      'Bhussi',
      'Chuttiana',
      'City Gojra',
      'City Kamalia',
      'City Toba',
      'Nawan Lahore',
      'Pir Mehal',
      'Rajana',
      'Saddar Gojra',
      'Saddar Kamalia',
      'Saddar Toba',
    ],
    Vehari: [
      'Adda Jhal Sial',
      'Anti-Corruption',
      'City Burewala',
      'City Mailsi',
      'City Vehari',
      'Danewal',
      'Fateh Shah',
      'FIA',
      'Gaggo',
      'Garah Morh',
      'Karam Pur',
      'Ludden',
      'Machiwal',
      'Meera Pur',
      'Mitroo',
      'Model Town',
      'Railway',
      'Saddar Burewala',
      'Saddar Mailsi',
      'Saddar Vehari',
      'Sahuka',
      'Sheikh Fazil',
      'Thingi',
      'Tibba Sultan Pur',
    ],
  },
  'Khyber Pakhtunkhwa': {
    Abbottabad: [
      'Bagnotar',
      'Bakot',
      'Cantt',
      'City',
      'Havelian',
      'Lora',
      'Mirpur',
      'Nara',
      'Nathiagali',
      'Nawansher',
      'Sherwan',
      'Women Police Station',
    ],
    Bajaur: [],
    Bannu: [
      'Bakka Khel',
      'Basya Khel',
      'Cantt',
      'Domel',
      'Ghori wala',
      'Jani Khel',
      'Johar',
      'Kaki',
      'Mairian',
      'Mandan',
      'Saddar',
      'Township',
    ],
    Batagram: [
      'Banna',
      'Battagram',
      'Changle',
      'Kuza Banda',
      'Pazang',
      'Shamlai',
    ],
    Buner: [
      'Chinglai',
      'Dagger',
      'Gul bandi',
      'Jawar',
      'Nawagai',
      'Ningarai',
      'Pir Baba',
      'Totalai',
    ],
    Charsadda: [
      'Battagram',
      'Charsadda',
      'Khanmai',
      'Khawajawas Koroona',
      'Mandani',
      'Nisatta',
      'Prang',
      'Sardheri',
      'Shabqadar',
      'Sro-Killi',
      'Tangi',
      'Tarnab',
      'Umarzai',
    ],
    'Dera Ismail Khan': [
      'Band Kurai',
      'Cantt',
      'Chodwan',
      'City',
      'Daraban',
      'Dera Town',
      'GomalUniversity',
      'Kirri Khaisore',
      'Kulachi',
      'Paharpur',
      'Panyala',
      'Paroa',
      'Saddar',
      'Yark',
    ],
    Hangu: ['Bilyamina', 'City Hangu', 'Doaba', 'Saddar', 'Thall'],
    Haripur: [
      'Beer',
      'Cantt',
      'City',
      'Ghazi',
      'Hattar',
      'K.T.S',
      'Khanpur',
      'Kotnajeebullah',
      'Nara Amazai',
      'Sarai Saleh',
    ],
    Karak: [
      'Bandadaud Shah',
      'Gurguri',
      'Karak',
      'Khuram',
      'Latambar',
      'Sabir Abad',
      'Shah Saleem',
      'Takhat Nasrati',
      'Terri',
    ],
    Khyber: [],
    Kohat: [
      'Bilitang',
      'Cantt',
      'Gumbat',
      'Jangalkhel',
      'Jarma',
      'Kaghazai',
      'KDA',
      'Lachi',
      'Saddar',
      'Shakardara',
      'Ustermzai',
    ],
    'Kolai Palas': [],
    Kurram: [],
    'Lakki Marwat': [
      'Dodiwala',
      'Ghazni Khel',
      'Lakki',
      'Naurang',
      'Pezu',
      'Tajori',
    ],
    'Lower Chitral': [
      'Arando',
      'Ayun',
      'Bumburate',
      'Buni',
      'Chitral',
      'Darosh',
      'Koghozi',
      'Lotkoh',
      'Mastooj',
      'Mulkoh',
      'Shaghoor',
      'Sher Koh',
    ],
    'Lower Dir': [
      'Asbnar',
      'Balambat',
      'Chakdara',
      'Hayaserai',
      'Khal',
      'Lal Qilla',
      'Mayar',
      'Munda',
      'Ouch',
      'Samar Bagh',
      'Talash',
      'Timergara',
      'Zimdara',
    ],
    'Lower Kohistan': [
      'Battera',
      'Dassu',
      'Dubair',
      'Herban',
      'Jalkot',
      'Karang',
      'Komella',
      'Looter',
      'Palas',
      'Pattan',
      'Sazeen',
    ],
    'Malakand Protected Area': [],
    Mansehra: [
      'Bafa',
      'Balakot',
      'Battale',
      'Cantt',
      'City',
      'Darband',
      'Garhi Habibullah',
      'Kaghan',
      'Khaki',
      'Lasan Nawab',
      'Oghi',
      'Pulra',
      'Shinkyari',
    ],
    Mardan: [
      'Choora',
      'City',
      'Garhi Kapura',
      'Hoti',
      'Jabbar',
      'Katlang',
      'Kharaki',
      'Lundkhuwar',
      'Par Hoti',
      'Rustam',
      'Saddar',
      'SaroShah',
      'ShahbazGarhi',
      'SheikhMaltoon',
      'SherGarh',
      'TakhtBhai',
      'Toru',
    ],
    Mohmand: [],
    'North Waziristan': [],
    Nowshera: [
      'AkbarPura',
      'Akora',
      'Azakhel',
      'Nizam pur',
      'Nowshera Cantt',
      'Nowshera Kalan',
      'Pabbi',
      'Risalpur',
    ],
    Orakzai: [],
    Peshawar: [
      'Badaber',
      'Bannamari',
      'Chamkani',
      'Daudzai',
      'Eastcantt',
      'Faqirabad',
      'Gulbahar',
      'Gulbarg',
      'Hashtnagri',
      'Hayatabad',
      'Kabuli',
      'Khazana',
      'Kotwali',
      'Mathra',
      'Mattani',
      'Michni Gate',
      'Nasirbagh',
      'Phandu',
      'Pharipura',
      'Pishtakhara',
      'Regi',
      'Sarband',
      'Shahqabool',
      'Suburb',
      'Tatara',
      'Tehkal',
      'UniversityTown',
      'Urmer',
      'Westcantt',
      'Women Police Station',
    ],
    Shangla: [
      'Aloch',
      'Alpuri',
      'Bisham',
      'Chakisar',
      'Kamach',
      'Karora',
      'Martong',
    ],
    'South Waziristan': [],
    Swabi: [
      'I.D.S',
      'Kalukhan',
      'Lahor',
      'Parmoli',
      'Swabi',
      'Topi',
      'Utla',
      'Yar Hussain',
      'Zaida',
    ],
    Swat: [
      'Banr',
      'Behrain',
      'Charbagh',
      'Chuprail',
      'Ghaligai',
      'Kabbal',
      'Kalakot',
      'Kalam',
      'Kanju',
      'Khwaza Khela',
      'Kokarai',
      'Madyan',
      'Malam Jabba',
      'Manglawar',
      'Matta',
      'Mingora',
      'Rahimabad',
      'Sadu Sharif',
      'Shah Dhari',
      'Shamozai',
    ],
    Tank: ['Gomal', 'Gul Imam', 'Mulazi', 'Tank'],
    Torghar: ['Darbani', 'Judbah', 'Karor'],
    'Upper Chitral': [
      'Arando',
      'Ayun',
      'Bumburate',
      'Buni',
      'Chitral',
      'Darosh',
      'Koghozi',
      'Lotkoh',
      'Mastooj',
      'Mulkoh',
      'Shaghoor',
      'Sher Koh',
    ],
    'Upper Dir': [
      'Barawal',
      'Dir',
      'Gandigar',
      'Jegum',
      'Kalkot',
      'Sahib abad',
      'Shahi Kot',
      'Sheringal',
      'Thal',
      'Wari',
    ],
    'Upper Kohistan': [
      'Battera',
      'Dassu',
      'Dubair',
      'Herban',
      'Jalkot',
      'Karang',
      'Komella',
      'Looter',
      'Palas',
      'Pattan',
      'Sazeen',
    ],
  },
  Sindh: {},
  Balochistan: {},
  'Azad Jammu & Kashmir': {},
  'Gilgit-Baltistan': {},
  'Islamabad Capital Territory': {},
} as const;

type SeedDistrict = {
  name: string;
  cities: string[];
};

type SeedProvince = {
  name: string;
  districts: SeedDistrict[];
};

export const PAKISTAN_GEO: SeedProvince[] = Object.entries(
  PAKISTAN_GEO_RAW,
).map(([provinceName, districts]) => ({
  name: provinceName,
  districts: Object.entries(districts).map(([districtName, cities]) => ({
    name: districtName,
    cities: [...cities],
  })),
}));
